### ISSUE TITLE
License the repository

### ISSUE THREAD

**Issue by IllusionMan1212** [codedrunks/BrewBot#70]
I highly suggest AGPL3

**Comment by Sv443** [comment]
I looked around a bit and found this one which only prohibits commercial use as far as I can tell  
https://commonsclause.com/  
  
<img width="611" alt="grafik" src="https://user-images.githubusercontent.com/38158426/189757671-da80aed8-8d0d-4331-a9bc-4fe08af50f59.png">

**Comment by Sv443** [comment]
AGPL is apparently too ambiguous and has loopholes

**Comment by IllusionMan1212** [comment]
I disagree. AGPL3 should have all the loopholes fixed and is a hard copyleft license. Commercial use is permitted tho, but source and modifications have to be disclosed. I don't mind that commercial use is fine. But idk about all y'all.

**Comment by Sv443** [comment]
I really despise same-license clauses but ig for this project it would be fine

**Comment by IllusionMan1212** [comment]
pog. @kofskie @geoday03 @canarado thoughts?

**Comment by Sv443** [comment]
agpl3 it is then?

**Comment by IllusionMan1212** [comment]
Ye

**Comment by Sv443** [comment]
adding it to my branch

**Comment by geoday03** [comment]
I don't think I checked my notifications until now
